### ISSUE TITLE
Fix data integrity job

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1071]
It has been failing integrity checks, and we haven't been notified :(

From last night:
```
20 Sep 2017 03:23:36.518128 <190>1 2017-09-20T07:23:35.148025+00:00 app scheduler.2954 - - Validating Assessments...
20 Sep 2017 03:23:36.518126 <190>1 2017-09-20T07:23:35.202258+00:00 app scheduler.2954 - - Validating Educators...
20 Sep 2017 03:23:41.442125 <190>1 2017-09-20T07:23:41.142957+00:00 app scheduler.2954 - - Validating Students...
20 Sep 2017 03:23:42.028116 <190>1 2017-09-20T07:23:41.744696+00:00 app scheduler.2954 - - rake aborted!
20 Sep 2017 03:23:42.028178 <190>1 2017-09-20T07:23:41.744710+00:00 app scheduler.2954 - - ActiveRecord::RecordInvalid: Validation failed: Grade must be a valid grade
20 Sep 2017 03:23:42.028220 <190>1 2017-09-20T07:23:41.745001+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/validations.rb:78:in `raise_validation_error'
20 Sep 2017 03:23:42.028203 <190>1 2017-09-20T07:23:41.745003+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/validations.rb:50:in `save!'
20 Sep 2017 03:23:42.028215 <190>1 2017-09-20T07:23:41.745003+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
20 Sep 2017 03:23:42.028214 <190>1 2017-09-20T07:23:41.745004+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:313:in `block in save!'
20 Sep 2017 03:23:42.028242 <190>1 2017-09-20T07:23:41.745005+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
20 Sep 2017 03:23:42.029256 <190>1 2017-09-20T07:23:41.745006+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
20 Sep 2017 03:23:42.029259 <190>1 2017-09-20T07:23:41.745007+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
20 Sep 2017 03:23:42.029250 <190>1 2017-09-20T07:23:41.745010+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
20 Sep 2017 03:23:42.029247 <190>1 2017-09-20T07:23:41.745011+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
20 Sep 2017 03:23:42.029211 <190>1 2017-09-20T07:23:41.745012+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:210:in `transaction'
20 Sep 2017 03:23:42.029233 <190>1 2017-09-20T07:23:41.745012+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
20 Sep 2017 03:23:42.029205 <190>1 2017-09-20T07:23:41.745013+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:313:in `save!'
20 Sep 2017 03:23:42.029202 <190>1 2017-09-20T07:23:41.745014+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/suppressor.rb:46:in `save!'
20 Sep 2017 03:23:42.029232 <190>1 2017-09-20T07:23:41.745014+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:63:in `block (2 levels) in find_each'
20 Sep 2017 03:23:42.029207 <190>1 2017-09-20T07:23:41.745015+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:63:in `each'
20 Sep 2017 03:23:42.029221 <190>1 2017-09-20T07:23:41.745016+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:63:in `block in find_each'
20 Sep 2017 03:23:42.029228 <190>1 2017-09-20T07:23:41.745017+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:129:in `block in find_in_batches'
20 Sep 2017 03:23:42.029223 <190>1 2017-09-20T07:23:41.745018+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:230:in `block in in_batches'
20 Sep 2017 03:23:42.030208 <190>1 2017-09-20T07:23:41.745018+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:214:in `loop'
20 Sep 2017 03:23:42.030214 <190>1 2017-09-20T07:23:41.745019+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:214:in `in_batches'
20 Sep 2017 03:23:42.030219 <190>1 2017-09-20T07:23:41.745020+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:128:in `find_in_batches'
20 Sep 2017 03:23:42.030212 <190>1 2017-09-20T07:23:41.745020+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation/batches.rb:62:in `find_each'
20 Sep 2017 03:23:42.030203 <190>1 2017-09-20T07:23:41.745021+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/querying.rb:9:in `find_each'
20 Sep 2017 03:23:42.030171 <190>1 2017-09-20T07:23:41.745021+00:00 app scheduler.2954 - - /app/app/reports/integrity_check.rb:26:in `block in has_valid_data?'
20 Sep 2017 03:23:42.030151 <190>1 2017-09-20T07:23:41.745022+00:00 app scheduler.2954 - - /app/app/reports/integrity_check.rb:24:in `each'
20 Sep 2017 03:23:42.030162 <190>1 2017-09-20T07:23:41.745023+00:00 app scheduler.2954 - - /app/app/reports/integrity_check.rb:24:in `has_valid_data?'
20 Sep 2017 03:23:42.030152 <190>1 2017-09-20T07:23:41.745023+00:00 app scheduler.2954 - - /app/app/reports/integrity_check.rb:5:in `check!'
20 Sep 2017 03:23:42.030173 <190>1 2017-09-20T07:23:41.745024+00:00 app scheduler.2954 - - /app/lib/tasks/report.rake:9:in `block (2 levels) in <top (required)>'
20 Sep 2017 03:23:42.030183 <190>1 2017-09-20T07:23:41.745025+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
20 Sep 2017 03:23:42.030189 <190>1 2017-09-20T07:23:41.745025+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
20 Sep 2017 03:23:42.030196 <190>1 2017-09-20T07:23:41.745026+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
20 Sep 2017 03:23:42.030188 <190>1 2017-09-20T07:23:41.745027+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
20 Sep 2017 03:23:42.030185 <190>1 2017-09-20T07:23:41.745028+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
20 Sep 2017 03:23:42.031208 <190>1 2017-09-20T07:23:41.745028+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
20 Sep 2017 03:23:42.031223 <190>1 2017-09-20T07:23:41.745029+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
20 Sep 2017 03:23:42.031206 <190>1 2017-09-20T07:23:41.745029+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
20 Sep 2017 03:23:42.031188 <190>1 2017-09-20T07:23:41.745030+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
20 Sep 2017 03:23:42.031208 <190>1 2017-09-20T07:23:41.745031+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
20 Sep 2017 03:23:42.031185 <190>1 2017-09-20T07:23:41.745034+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
20 Sep 2017 03:23:42.031197 <190>1 2017-09-20T07:23:41.745035+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
20 Sep 2017 03:23:42.031213 <190>1 2017-09-20T07:23:41.745036+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
20 Sep 2017 03:23:42.031188 <190>1 2017-09-20T07:23:41.745036+00:00 app scheduler.2954 - - /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
20 Sep 2017 03:23:42.031130 <190>1 2017-09-20T07:23:41.745037+00:00 app scheduler.2954 - - /app/bin/bundle:3:in `load'
20 Sep 2017 03:23:42.031132 <190>1 2017-09-20T07:23:41.745038+00:00 app scheduler.2954 - - /app/bin/bundle:3:in `<main>'
20 Sep 2017 03:23:42.031138 <190>1 2017-09-20T07:23:41.745039+00:00 app scheduler.2954 - - Tasks: TOP => report:data_integrity
20 Sep 2017 03:23:42.031148 <190>1 2017-09-20T07:23:41.745039+00:00 app scheduler.2954 - - (See full trace by running task with --trace)
20 Sep 2017 03:23:42.031188 <190>1 2017-09-20T07:23:41.856031+00:00 app scheduler.2954 - - [Scout] [09/20/17 07:23:41 +0000 scheduler.2954 (4)] INFO : Shutting down Scout Agent
20 Sep 2017 03:23:42.031185 <190>1 2017-09-20T07:23:41.856059+00:00 app scheduler.2954 - - [Scout] [09/20/17 07:23:41 +0000 scheduler.2954 (4)] INFO : Shutting down ScoutApm
20 Sep 2017 03:23:42.103189 <190>1 2017-09-20T07:23:41.856097+00:00 app scheduler.2954 - - [Scout] [09/20/17 07:23:41 +0000 scheduler.2954 (4)] INFO : Stopping background worker
20 Sep 2017 03:23:42.323138 <45>1 2017-09-20T07:23:42.002701+00:00 heroku scheduler.2954 - - State changed from up to complete
20 Sep 2017 03:23:42.829133 <45>1 2017-09-20T07:23:41.989833+00:00 heroku scheduler.2954 - - Process exited with status 1
```

**Comment by kevinrobinson** [comment]
Alternately, we could remove this.  But also worth investigating the records in the database that are violating the constraints and if that's still actively happening for new records.

**Comment by kevinrobinson** [comment]
It'd be great to add this in; drift between db state and current validations has happened a few times.  Running this just needs per-model optimizations.

To move this forward:
1. Move the rake task into a plain class in `lib`
2. Add a `PerfTest` case for it and note how long it takes locally when `MORE_DEMO_STUDENTS=true`
3. Iteratively add optimizations to model classes.
