### ISSUE TITLE
Can't edit educator field in admin page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1193]
From trying to manual test features in IE11 for https://github.com/studentinsights/studentinsights/pull/1182.

### What I tried - check three grade levels
<img width="1246" alt="screen shot 2017-10-25 at 12 05 57 am" src="https://user-images.githubusercontent.com/1056957/31980117-75099e82-b918-11e7-9564-1aac122ec019.png">

### What happened
<img width="1250" alt="screen shot 2017-10-25 at 12 07 33 am" src="https://user-images.githubusercontent.com/1056957/31980127-8536a28c-b918-11e7-807b-ea58a29bec44.png">

### More details
```
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field" id="grade-level-access-field">
  <% @valid_grades.each.with_index do |grade, index| %>
    <span style="width: 60px; display: inline-block;">
      <input type="checkbox"
             name="educator[grade_level_access][<%= grade %>]"
             <%= field.checkbox_on?(grade) %>
```

logs:
```
Started PATCH "/admin/educators/1" for 127.0.0.1 at 2017-10-25 00:06:02 -0400
[0] Processing by Admin::EducatorsController#update as HTML
[0]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"jbSk/DBcwN+R0SSVJ++N73cCLVPaKQmYztru/GIkY3jksj7yum+BlYJZeZSY4PToET6QQg3BrciaO3Or4BSw2g==", "educator"=>{"schoolwide_access"=>"1", "grade_level_access"=>{"PK"=>"on", "KF"=>"on", "SP"=>"on"}, "restricted_to_sped_students"=>"0", "restricted_to_english_language_learners"=>"0", "can_view_restricted_notes"=>"1"}, "commit"=>"Update Educator", "id"=>"1"}
[0]   Educator Load (0.7ms)  SELECT  "educators".* FROM "educators" WHERE "educators"."id" = $1 ORDER BY "educators"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
[0]   Educator Load (0.8ms)  SELECT  "educators".* FROM "educators" WHERE "educators"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[0]    (0.4ms)  BEGIN
[0]   Educator Exists (0.7ms)  SELECT  1 AS one FROM "educators" WHERE "educators"."email" = $1 AND ("educators"."id" != $2) LIMIT $3  [["email", "demo@example.com"], ["id", 1], ["LIMIT", 1]]
[0]   School Load (0.5ms)  SELECT  "schools".* FROM "schools" WHERE "schools"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[0]    (0.2ms)  ROLLBACK
[0]   Rendering /Users/krobinson/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/app/views/administrate/application/edit.html.erb within layouts/administrate/application
[0]   Rendered fields/yes_no_boolean_field/_form.html.erb (0.9ms)
[0]   Rendered fields/postgres_array_field/_form.html.erb (3.4ms)
[0]   Rendered /Users/krobinson/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/app/views/administrate/application/_form.html.erb (8.9ms)
[0]   Rendered /Users/krobinson/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/app/views/administrate/application/edit.html.erb within layouts/administrate/application (21.4ms)
[0] Completed 500 Internal Server Error in 58ms (ActiveRecord: 3.4ms)
[0]
[0]
[0]
[0] NoMethodError - undefined method `each' for nil:NilClass:
[0]   app/views/fields/postgres_array_field/_form.html.erb:5:in `_app_views_fields_postgres_array_field__form_html_erb__3162027539175522246_70263822342380'
[0]   actionview (5.1.3) lib/action_view/template.rb:157:in `block in render'
[0]   activesupport (5.1.3) lib/active_support/notifications.rb:168:in `instrument'
[0]   actionview (5.1.3) lib/action_view/template.rb:352:in `instrument_render_template'
[0]   actionview (5.1.3) lib/action_view/template.rb:155:in `render'
[0]   actionview (5.1.3) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
[0]   actionview (5.1.3) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[0]   activesupport (5.1.3) lib/active_support/notifications.rb:166:in `block in instrument'
[0]   activesupport (5.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[0]   activesupport (5.1.3) lib/active_support/notifications.rb:166:in `instrument'
[0]   actionview (5.1.3) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
[0]   actionview (5.1.3) lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
[0]   actionview (5.1.3) lib/action_view/renderer/partial_renderer.rb:310:in `render'
[0]   actionview (5.1.3) lib/action_view/renderer/renderer.rb:47:in `render_partial'
[0]   actionview (5.1.3) lib/action_view/renderer/renderer.rb:21:in `render'
[0]   actionview (5.1.3) lib/action_view/helpers/rendering_helper.rb:32:in `render'
[0]   administrate (0.8.1) app/helpers/administrate/application_helper.rb:7:in `render_field'
[0]   administrate (0.8.1) app/views/administrate/application/_form.html.erb:35:in `block (2 levels) in ___sers_krobinson__rbenv_versions_______lib_ruby_gems_______gems_administrate_______app_views_administrate_application__form_html_erb__1284078369629406575_70263822622060'
[0]   administrate (0.8.1) app/views/administrate/application/_form.html.erb:33:in `each'
[0]   administrate (0.8.1) app/views/administrate/application/_form.html.erb:33:in `block in ___sers_krobinson__rbenv_versions_______lib_ruby_gems_______gems_administrate_______app_views_administrate_application__form_html_erb__1284078369629406575_70263822622060'
[0]   actionview (5.1.3) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
[0]   actionview (5.1.3) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
[0]   actionview (5.1.3) lib/action_view/helpers/capture_helper.rb:39:in `capture'
[0]   actionview (5.1.3) lib/action_view/helpers/form_helper.rb:450:in `form_for'
[0]   administrate (0.8.1) app/views/administrate/application/_form.html.erb:17:in `___sers_krobinson__rbenv_versions_______lib_ruby_gems_______gems_administrate_______app_views_administrate_application__form_html_erb__1284078369629406575_70263822622060'
[0]   actionview (5.1.3) lib/action_view/template.rb:157:in `block in render'
[0]   activesupport (5.1.3) lib/active_support/notifications.rb:168:in `instrument'
[0]   actionview (5.1.3) lib/action_view/template.rb:352:in `instrument_render_template'
[0]   actionview (5.1.3) lib/action_view/template.rb:155:in `render'
[0]   actionview (5.1.3) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
[0]   actionview (5.1.3) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[0]   activesupport (5.1.3) lib/active_support/notifications.rb:166:in `block in instrument'
[0]   activesupport (5.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[0]   activesupport (5.1.3) lib/active_support/notifications.rb:166:in `instrument'
```

**Comment by kevinrobinson** [comment]
stale, no longer an issue
