### ISSUE TITLE
Importer: Error with parsing related to quotes

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1738]
Could be part of https://github.com/studentinsights/studentinsights/issues/1626.

Unclosed quoted field on line 4719.

```
 /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1898:in `block in shift'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1805:in `loop'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1805:in `shift'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1747:in `each'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1761:in `to_a'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1761:in `read'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1307:in `parse'
	/app/app/importers/data_transformers/csv_transformer.rb:21:in `transform'
	/app/app/importers/file_importers/csv_downloader.rb:15:in `get_data'
	/app/app/importers/file_importers/behavior_importer.rb:13:in `import'
	/app/app/importers/import_task.rb:136:in `block in import_all_the_data'
	/app/app/importers/import_task.rb:129:in `each'
	/app/app/importers/import_task.rb:129:in `import_all_the_data'
	/app/app/importers/import_task.rb:29:in `connect_transform_import'
	/app/app/jobs/import_job.rb:9:in `perform'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:81:in `block in invoke_job'
	/app/vendor/bundle/ruby/2.3.0/gems/rollbar-2.15.5/lib/rollbar/plugins/delayed_job/plugin.rb:38:in `block in invoke_job_callback'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-2.4.10/lib/scout_apm/background_job_integrations/delayed_job.rb:71:in `block (3 levels) in install'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:78:in `invoke_job'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block (2 levels) in run'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block in run'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:229:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:213:in `block in work_off'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `times'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `work_off'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:175:in `block (4 levels) in start'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:174:in `block (3 levels) in start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:173:in `block (2 levels) in start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `loop'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `block in start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:171:in `start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
	/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
	/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
	/app/bin/bundle:3:in `load'
	/app/bin/bundle:3:in `<main>'
    
        {
  "importer": "BehaviorImporter"
}
```

**Comment by kevinrobinson** [comment]
Tried poking around this to see if I could see anything in the CSVs, but can't find anything irregular right now.  Here's the scripts for poking around at counting quotes on each line and unquoted `\N` fields (Somerville only).

```
$ cat assessment_export.txt | head -n 100 | grep -o '"' | wc -l
$ cat assessment_export.txt | head -n 100 | grep -o '\\N' | wc -l
$ N=20000000; A=$(cat assessment_export.txt | head -n $N | grep -o '"' | wc -l); B=$(cat assessment_export.txt | head -n $N | grep -o '\\N' | wc -l); echo $(( $A/2 + $B ))
```

**Comment by kevinrobinson** [comment]
One hypothesis is that this is related to https://github.com/studentinsights/studentinsights/issues/1626, and that this might be happening because the Insights job tries to copy the file while it’s in the middle of being written.

That might explain why it’s happening recently (the importer is unhealthy and running more frequently - normally we manually schedule when it runs so both things don’t happen at the same
time).   It would also explain why it only happens intermittently and not on every import run.

**Comment by kevinrobinson** [comment]
With https://github.com/studentinsights/studentinsights/pull/1858, going to consider this resolved.  This hasn't come up again.  If it's related to https://github.com/studentinsights/studentinsights/issues/1626, we'll notice as we fix those up.  If it's something separate, it will come up and alert again :)
