### ISSUE TITLE
Improve StudentsImporter to handle students with no grade set

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1775]
from this:
```
Validation failed: Grade invalid grade:

      /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/validations.rb:78:in `raise_validation_error'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/validations.rb:50:in `save!'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:313:in `block in save!'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:313:in `save!'
	/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/suppressor.rb:46:in `save!'
	/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:354:in `save!'
	/app/app/importers/file_importers/students_importer.rb:44:in `import_row'
	/app/app/importers/file_importers/students_importer.rb:16:in `block in import'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:852:in `each'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:852:in `each'
	/app/app/importers/file_importers/students_importer.rb:15:in `each_with_index'
	/app/app/importers/file_importers/students_importer.rb:15:in `import'
	/app/app/importers/import_task.rb:136:in `block in import_all_the_data'
	/app/app/importers/import_task.rb:129:in `each'
	/app/app/importers/import_task.rb:129:in `import_all_the_data'
	/app/app/importers/import_task.rb:29:in `connect_transform_import'
	/app/app/jobs/import_job.rb:9:in `perform'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:81:in `block in invoke_job'
	/app/vendor/bundle/ruby/2.3.0/gems/rollbar-2.15.5/lib/rollbar/plugins/delayed_job/plugin.rb:38:in `block in invoke_job_callback'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-2.4.10/lib/scout_apm/background_job_integrations/delayed_job.rb:71:in `block (3 levels) in install'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:78:in `invoke_job'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block (2 levels) in run'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block in run'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:229:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:213:in `block in work_off'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `times'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `work_off'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:175:in `block (4 levels) in start'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:174:in `block (3 levels) in start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:173:in `block (2 levels) in start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `loop'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `block in start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:171:in `start'
	/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.4/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
	/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
	/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
	/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
	/app/bin/bundle:3:in `load'
	/app/bin/bundle:3:in `<main>'
    
        {
  "importer": "StudentsImporter"
}
```

**Comment by kevinrobinson** [comment]
From looking at the import data in Somerville, this is from 13 students all withdrawn or graduated.  https://github.com/studentinsights/studentinsights/pull/1776 is a fix.

**Comment by kevinrobinson** [comment]
https://github.com/studentinsights/studentinsights/pull/1776 fixed this.
